version: '2'
services:
  peer-base:
    image: hyperledger/fabric-peer
    dns_search: .
    environment:
      - CORE_PEER_TLS_ENABLED=false
      - CORE_LOGGING_LEVEL=WARNING
      - CORE_NEXT=true
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1:7051
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=compose_chaintool
      - CORE_PEER_ADDRESSAUTODETECT=true
    volumes:
      - /var/run/:/host/var/run/
    command: peer node start